group: edge

services:
  - docker

cache:
  directories:
#    - $HOME/.m2/

language: java

stages:
  - name: build

install: skip

jobs:
  include:
  - stage: build
    name: "Build Unomi"
    jdk: openjdk8
    script:
    - ./buildAndRunTests.sh