group: edge

services:
  - docker

cache:
  directories:
    - $HOME/.m2/

language: java

stages:
  - name: build
    if: branch != releases
  - name: build and deploy
    if: branch = releases

install: skip

jobs:
  include:
  - stage: build
    name: "Build Unomi"
    jdk: openjdk8
    script:
    - ./build.sh
  - stage: build and deploy
    name: "Build and deploy Unomi"
    jdk: openjdk8
    script:
      - ./buildAndDeploy.sh